source 'https://rubygems.org'
ruby '2.2.0'
gem 'hobbit'
gem 'hobbit-hole'
gem 'mote-angular'
gem 'rack-protection'
gem 'bcrypt-ruby'
gem 'pg'
gem 'sequel'
group :test do
  gem 'shotgun'
  gem 'launchy'
  gem 'rspec'
  gem 'capybara'
end
